name: Render README

on:
  push:
    paths:
      - "README.qmd"
      - ".github/workflows/readme.yaml"
  pull_request:
    paths:
      - "README.qmd"
      - ".github/workflows/readme.yaml"

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Enable caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-groups

      - name: Render README.qmd
        run: quarto render README.qmd

      - name: Commit changes (only on push)
        if: github.event_name == 'push'
        run: |
          if git diff --quiet README.md; then
            echo "No changes to commit."
          else
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: auto-update README.md"
            git push
          fi
